Raise error if max slices smaller than one slice plus padding slices
See the following PR comments for a discussion on what could be done in
the future to try and salvage the pipeline run instead of raising an
error: https://github.com/DiamondLightSource/httomo/pull/680.